### PR TITLE
Add assertThrows

### PR DESCRIPTION
**Pull request by hdgarrood**
I'm currently trying to improve the compiler test suite, and so this is to replace `assertPartial` in the test prelude. This will probably be useful more generally too, though.

### CODE REVIEW

**Comment by garyb** [comment]
Could you add a comment to the new function(s) please? Also, shouldn't we be using `Eff (err :: EXCEPTION | eff)` there rather than `Unit -> a` really?

**Comment by hdgarrood** [comment]
The idea behind this was, if you have something which is `Eff (err :: EXCEPTION | eff) a`, then it's easy to check whether it throws an exception, using `catchException`. On the other hand, there's no obvious way to check whether "pure" code will throw an exception.

**Comment by garyb** [comment]
In what situation would you want pure code to throw an exception? :smile:

**Comment by hdgarrood** [comment]
To make sure that an unsafe function does what you want it to? Eg `assertThrows $ unsafeIndex -1 xs`? The specific use case I was thinking of is here: https://github.com/purescript/purescript/blob/master/examples/passing/PartialFunction.purs

**Comment by garyb** [comment]
Gotcha, that makes sense. Perhaps we should mention something like that in the comment too then ("this is for testing unsafe functions" or whtever), as I think `assertThrows` actually can't be used to test `Eff`-based exceptions with this type signature.

**Comment by hdgarrood** [comment]
:+1:

**Comment by garyb** [comment]
Great, thanks!

Oh, er, one last thing - can you remove the `import Control.Monad.Eff.Exception (EXCEPTION())`? It's breaking in travis as `-assert` doesn't depend on `-exceptions` currently :wink:

**Comment by garyb** [comment]
:+1:

**Pull request merged**
