### PR TITLE
Add some helper functions

### LINKED ISSUE #5: Can we make assertion output more readable?
Some libraries outside of core use this library as their way of testing. The problem is that the output is pretty hard to understand. How would we feel about adding a few small helpers to make the output better?

```PureScript
assertEqual ∷ forall a eff. Eq a => Show a => { expected :: a, actual :: a } -> Eff (assert :: ASSERT | eff) Unit
assertEqual {actual, expected} = do
  unless result $ log message
  assert' message result
  where
  message = "Expected: " <> show expected <> "\nActual:   " <> show actual
  result = actual == expected

assertTrue :: forall eff. Boolean -> Eff (assert :: ASSERT | eff) Unit
assertTrue actual = assertEqual { actual, expected: true }

assertFalse :: forall eff. Boolean -> Eff (assert :: ASSERT | eff) Unit
assertFalse actual = assertEqual { actual, expected: false }
```

### PR DESCRIPTION
**Pull request by joneshf**
Should close #5.

Let me know if there's anything that should change.

### CODE REVIEW

**Comment by LiamGoodacre** [comment]
:+1: except that you also need to export the declarations!

**Comment by joneshf** [comment]
Whoops! Thanks for the review!

**Comment by joneshf** [comment]
How are things looking now?

**Comment by LiamGoodacre** [comment]
Thanks!

**Pull request merged**
